server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://172.18.40.108:3306/czhy-feature?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true
    username: pcloud
    password: pcloud
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 1234