# 配置服务端口号
server:
  port: 8082
# 配置数据库信息
spring:
  datasource:
    url: jdbc:mysql://***:***/czhy-dev?useUnicode=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=true
    username: ***
    password: ***
# Mybatis-plus 插件配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # sql打印配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl